-- Database schema for Petrol Pump Management System

-- Create PETROLPUMP table
CREATE TABLE IF NOT EXISTS PETROLPUMP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    CITY TEXT,
    PINCODE TEXT,
    REGISTRATION TEXT,
    EMAIL TEXT,
    PHONE TEXT,
    STATE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create USER table
CREATE TABLE IF NOT EXISTS USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    FNAME TEXT,
    LNAME TEXT,
    ADDRESS TEXT,
    PHONE TEXT,
    EMAIL TEXT,
    ADHAAR TEXT,
    PASSWORD TEXT,
    PIC TEXT,
    ACTIVE INTEGER DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create ROLE table
CREATE TABLE IF NOT EXISTS ROLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TYPE TEXT NOT NULL,
    PID INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create USER_ROLE table
CREATE TABLE IF NOT EXISTS USER_ROLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    USER_ID INTEGER,
    ROLE_ID INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);

-- Create COLLECTION_MODE table
CREATE TABLE IF NOT EXISTS COLLECTION_MODE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    MODE TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create PRODUCT table
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    
    -- 0 = Non-Fuel, 1 = Fuel
    TYPE INTEGER NOT NULL CHECK (TYPE IN (0,1)),

    PRICE REAL DEFAULT 0,

    -- If 1 = Stock managed via inventory ledger
    -- If 0 = Ignore stock (services, etc.)
    MANAGE_STOCK INTEGER DEFAULT 1 CHECK (MANAGE_STOCK IN (0,1)),

    ACTIVE INTEGER DEFAULT 1 CHECK (ACTIVE IN (0,1)),

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);
-- Create TANK_METADATA table
CREATE TABLE IF NOT EXISTS TANK_METADATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    CAPACITY REAL,
    TYPE TEXT,
    ACTIVE INTEGER DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create NOZZLE table
CREATE TABLE IF NOT EXISTS NOZZLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    NOZZLE_NUMBER INTEGER,
    TYPE TEXT,
    ACTIVE INTEGER DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create SHIFT_METADATA table
CREATE TABLE IF NOT EXISTS SHIFT_METADATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    STARTTIME TEXT,
    ENDTIME TEXT,
    SHIFT_TYPE TEXT,
    SID INTEGER,
    ACTIVE INTEGER DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (SID) REFERENCES USER(ID)
);

-- Create SHIFT table
CREATE TABLE IF NOT EXISTS SHIFT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    SHIFT_META_DATA_ID INTEGER,
    SUPERVISOR_ID INTEGER,
    START_TIME DATETIME,
    END_TIME DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (SHIFT_META_DATA_ID) REFERENCES SHIFT_METADATA(ID),
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES USER(ID)
);

-- Create SHIFT_NOZZLE_DSM table
CREATE TABLE IF NOT EXISTS SHIFT_NOZZLE_DSM (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    SHIFT_ID INTEGER,
    NOZZLE_ID INTEGER,
    USER_ID INTEGER,
    DOR REAL DEFAULT 0,
    DCR REAL DEFAULT 0,
    AOR REAL DEFAULT 0,
    ACR REAL DEFAULT 0,
    PUMP_TEST REAL DEFAULT 0,
    SELF REAL DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT(ID),
    FOREIGN KEY (NOZZLE_ID) REFERENCES NOZZLE(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

-- Create SHIFT_COLLECTION table
CREATE TABLE IF NOT EXISTS SHIFT_COLLECTION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SHIFT_NOZZLE_DSM_ID INTEGER,
    COLLECTION_MODE_ID INTEGER,
    AMOUNT REAL,
    PID INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SHIFT_NOZZLE_DSM_ID) REFERENCES SHIFT_NOZZLE_DSM(ID),
    FOREIGN KEY (COLLECTION_MODE_ID) REFERENCES COLLECTION_MODE(ID),
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create TANK table
CREATE TABLE IF NOT EXISTS TANK (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    TANK_ID INTEGER,
    SHIFT_ID INTEGER,
    OPEN_READING REAL DEFAULT 0,
    CLOSE_READING REAL DEFAULT 0,
    FUEL_RECEIVED REAL DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (TANK_ID) REFERENCES TANK_METADATA(ID),
    FOREIGN KEY (SHIFT_ID) REFERENCES SHIFT(ID)
);

-- Create SHIFT_PRICE table
CREATE TABLE  IF NOT EXISTS SHIFT_PRICE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    SID INTEGER,
    PRO_ID INTEGER,
    PRICE REAL,
    QTY INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (SID) REFERENCES SHIFT(ID),
    FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(ID)
);

-- Create FUEL_RECEIPT table
CREATE TABLE IF NOT EXISTS FUEL_RECEIPT (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PID INTEGER,
  TT TEXT,
  TID INTEGER,
  PRO_ID INTEGER,
  INVOICE_NO TEXT,
  INVOICE_DATE TEXT,
  INVOICE_AMOUNT REAL,
  INVOICE_QTY REAL,
  INVOICE_TEMP REAL,
  RO_TEMP REAL,
  INVOICE_DENSITY REAL,
  RO_COMPOSITE_DENSITY REAL,
  TVA REAL,
  SHORT_REPORT TEXT,
  FREIGHT_INVOICE_NO TEXT,
  FREIGHT_INVOICE_AMOUNT REAL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
-- Create TRANSPORT table
CREATE TABLE IF NOT EXISTS TRANSPORT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    VEHICLE_NUMBER TEXT,
    DRIVER_NAME TEXT,
    PHONE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)

);
-- Create ICREDIT table
CREATE TABLE IF NOT EXISTS ICREDIT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    CUSTOMER_NAME TEXT,
    VEHICLE_NUMBER TEXT,
    AMOUNT REAL,
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create CREDIT table
CREATE TABLE IF NOT EXISTS CREDIT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    BALANCE REAL DEFAULT 0,
    ACTIVE INTEGER DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);

-- Create BALANCE table
CREATE TABLE IF NOT EXISTS BALANCE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    CRDB INTEGER,
    BAL REAL,
    MODE INTEGER,
    SID INTEGER,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID),
    FOREIGN KEY (MODE) REFERENCES COLLECTION_MODE(ID)
);

-- Create REMINDER table
CREATE TABLE IF NOT EXISTS REMINDER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER,
    TASK TEXT NOT NULL,
    REMINDER_DATE DATE NOT NULL,
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACTIVE INTEGER DEFAULT 1,
    FOREIGN KEY (PID) REFERENCES PETROLPUMP(ID)
);
-- Create DATASHEET table

CREATE TABLE DATASHEET (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TANK_METADATA_ID INTEGER NOT NULL,
  HEIGHT INTEGER NOT NULL,
  CMV REAL NOT NULL,
  MMV REAL NOT NULL,
  UNIQUE (TANK_METADATA_ID, HEIGHT),
  FOREIGN KEY (TANK_METADATA_ID) REFERENCES TANK_METADATA(ID)
);-- FUEL_RATE table (SQLite)

CREATE TABLE IF NOT EXISTS FUEL_RATE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER NOT NULL,
    PRODUCT_TYPE TEXT NOT NULL CHECK (PRODUCT_TYPE IN ('HSD','MS','EBMS')),
    RATE REAL NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    UNIQUE (PID, PRODUCT_TYPE, EFFECTIVE_FROM)
);

-- INVENTORY_LEDGER table (SQLite)
CREATE TABLE IF NOT EXISTS INVENTORY_LEDGER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER NOT NULL,
    PRODUCT_TYPE TEXT NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    ENTRY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    SOURCE_TYPE TEXT NOT NULL CHECK (
        SOURCE_TYPE IN (
            'OPENING',
            'SHIFT_SALE',
            'PURCHASE',
            'ADJUSTMENT',
            'TRANSFER_IN',
            'TRANSFER_OUT',
            'POS_SALE'
        )
    ),
    SOURCE_ID INTEGER,
    QTY REAL NOT NULL,
    RATE REAL DEFAULT 0,
    AMOUNT REAL DEFAULT 0,
    REMARK TEXT,
    CREATED_BY INTEGER
);

CREATE INDEX IF NOT EXISTS IDX_LEDGER_PID_PRODUCT_DATE
ON INVENTORY_LEDGER (PID, PRODUCT_TYPE, TRANSACTION_DATE);
-- STOCK_SNAPSHOT table (SQLite)
CREATE TABLE IF NOT EXISTS STOCK_SNAPSHOT ( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER, 
    PRODUCT_TYPE TEXT, 
    STOCK REAL, 
    LAST_UPDATED DATETIME ); 

-- INVENTORY_ADJUSTMENT table (SQLite)
CREATE TABLE IF NOT EXISTS INVENTORY_ADJUSTMENT ( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    PID INTEGER, 
    PRODUCT_TYPE TEXT, 
    QTY REAL, 
    TRANSACTION_DATE DATETIME, 
    REMARK TEXT, 
    CREATED_BY INTEGER, 
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP );
-- POS_BILL table (SQLite)
  CREATE TABLE IF NOT EXISTS POS_BILL (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PID INTEGER NOT NULL,
    SHIFT_ID INTEGER NOT NULL,
    BILL_NO TEXT NOT NULL,
    CASHIER_ID INTEGER NOT NULL,
    SUBTOTAL REAL DEFAULT 0,
    DISCOUNT REAL DEFAULT 0,
    TOTAL REAL DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
-- POS_BILL_ITEM table (SQLite)
CREATE TABLE IF NOT EXISTS POS_BILL_ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    BILL_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QTY REAL NOT NULL,
    PRICE REAL NOT NULL,
    TOTAL REAL NOT NULL
);